// LFmall Exhibition Wireframe: BADGE
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["BADGE"] = {
                  "moduleCode":  "MD3",
                  "name":  "행사뱃지 (BADGE)",
                  "wireframeHtml":  "<div class=\u0027lfm-badge-card\u0027 style=\u0027font-family: \"Malgun Gothic\", \"Apple SD Gothic Neo\", sans-serif; background-color: #ffffff; width: 100%; box-sizing: border-box; padding: 40px 24px; text-align: center; border: 1px solid var(--hairline);\u0027><style>.lfm-badge-card .badge-title { font-size: 32px; font-weight: 900; color: #000000; line-height: 1.25; letter-spacing: -1.5px; margin: 0 0 16px 0; word-break: keep-all; }.lfm-badge-card .badge-subtitle { font-size: 14px; color: #888888; line-height: 1.5; margin: 0 0 28px 0; letter-spacing: -0.5px; }.lfm-badge-card .badge-banner { background: #000000; padding: 24px 20px; display: flex; gap: 16px; align-items: center; text-align: left; box-sizing: border-box; max-width: 560px; margin: 0 auto; }.lfm-badge-card .badge-logo-box { width: 76px; height: 76px; background: #f15a22; display: flex; align-items: center; justify-content: center; flex-shrink: 0; box-sizing: border-box; }.lfm-badge-card .badge-logo-text { font-family: \"Arial\", sans-serif; font-weight: 900; color: #ffffff; display: flex; align-items: flex-start; line-height: 1; font-size: 46px; }.lfm-badge-card .badge-logo-plus { font-size: 28px; margin-left: 2px; font-weight: 700; line-height: 0.8; margin-top: 4px; }.lfm-badge-card .badge-desc-box { flex: 1; min-width: 0; }.lfm-badge-card .badge-desc-text { font-size: 12.5px; color: #ffffff; line-height: 1.5; margin: 0; letter-spacing: -0.3px; word-break: keep-all; }@media (max-width: 480px) { .lfm-badge-card .badge-title { font-size: 24px; } .lfm-badge-card .badge-banner { padding: 16px; } .lfm-badge-card .badge-logo-box { width: 60px; height: 60px; } .lfm-badge-card .badge-logo-text { font-size: 36px; } .lfm-badge-card .badge-logo-plus { font-size: 20px; } .lfm-badge-card .badge-desc-text { font-size: 11px; } }.title-sec { text-align: center; padding: 24px 16px 12px 16px; }.title-main { font-size: 24px; font-weight: 800; color: var(--near-black); letter-spacing: -0.8px; margin: 0; }.title-sub { font-size: 13px; color: var(--slate); margin: 6px 0 0 0; }</style><div class='title-sec'><h3 class='title-main'>L+Day 뱃지 혜택</h3><p class='title-sub'>뱃지가 부착된 상품을 구매하고 특별한 추가 혜택을 누리세요!</p></div><div class=\u0027badge-banner\u0027><div class=\u0027badge-logo-box\u0027><div class=\u0027badge-logo-text\u0027>L<span class=\u0027badge-logo-plus\u0027>+</span></div></div><div class=\u0027badge-desc-box\u0027><p class=\u0027badge-desc-text\u0027>L+Day 뱃지가 있는 상품에 한하여 쿠폰 및<br>적립혜택이 적용됩니다. 뱃지가 떨어지기 전에<br>이 모든 혜택을 즐겨보세요!</p></div></div></div>"
              };
