// LFmall Exhibition Wireframe: BANNER
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["BANNER"] = {
                       "moduleCode":  "MD12",
                       "name":  "배너 (BANNER)",
                       "wireframeHtml":  "<div class='lfmall-banner-wf' style='border: 1px solid var(--hairline); background: var(--canvas-white); font-family: \"Malgun Gothic\", \"Apple SD Gothic Neo\", sans-serif; box-shadow: 0 12px 30px rgba(0,0,0,0.02); overflow: hidden; display: flex; flex-direction: column; width: 100%; border-radius: 0;'><style>.lfmall-banner-wf .title-sec { text-align: center; padding: 24px 16px 12px 16px; }.lfmall-banner-wf .title-main { font-size: 24px; font-weight: 800; color: var(--near-black); letter-spacing: -0.8px; margin: 0; }.lfmall-banner-wf .title-sub { font-size: 13px; color: var(--slate); margin: 6px 0 0 0; }.lfmall-banner-wf .img-wrap { width: 100%; position: relative; overflow: hidden; display: flex; align-items: center; justify-content: center; }.desktop-mockup .lfmall-banner-wf .img-wrap { aspect-ratio: 16/9; }.phone-mockup .lfmall-banner-wf .img-wrap { aspect-ratio: 1/1; }.lfmall-banner-wf .img-wrap img { width: 100%; height: 100%; object-fit: cover; }.lfmall-banner-wf .btn-action { display: block; width: 100%; max-width: 180px; margin: 16px auto 24px auto; padding: 12px 0; background: var(--near-black); color: var(--canvas-white); border-radius: 0; font-size: 12px; font-weight: 700; text-align: center; cursor: pointer; border: none; text-decoration: none; }.title-sec { text-align: center; padding: 24px 16px 12px 16px; }.title-main { font-size: 24px; font-weight: 800; color: var(--near-black); letter-spacing: -0.8px; margin: 0; }.title-sub { font-size: 13px; color: var(--slate); margin: 6px 0 0 0; }</style><div class='title-sec'><h3 class='title-main'>SUMMER LOOKBOOK</h3><p class='title-sub'>가볍고 시원하게 즐기는 서머 스타일링 가이드</p></div><div class='img-wrap'><img src='https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80' alt='배너 이미지' onerror=\"this.src='data:image/svg+xml;utf8,<svg xmlns=\\\'http://www.w3.org/2000/svg\\\' width=\\\'800\\\' height=\\\'450\'><rect width=\\\'800\\\' height=\\\'450\\\' fill=\'%23eeece7\'/><text x=\'50%\' y=\'50%\' font-size=\'24\' fill=\'%2375758a\' text-anchor=\'middle\'>LFmall Banner</text></svg>';\"></div><a href='#' class='btn-action' onclick=\"alert('기획전 페이지로 이동합니다.'); return false;\">바로가기 &rarr;</a></div>"
                   };
