// LFmall Exhibition Wireframe: COMMENT
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["COMMENT"] = {
                       "moduleCode":  "MD3",
                       "name":  "댓글 (COMMENT)",
                       "wireframeHtml":  "<div class='lfmall-comment-wf' style='border: 1px solid var(--hairline); background: var(--canvas-white); font-family: \"Malgun Gothic\", \"Apple SD Gothic Neo\", sans-serif; box-shadow: 0 12px 30px rgba(0,0,0,0.02); padding: 24px 20px; border-radius: 0;'><style>.lfmall-comment-wf .comm-title { font-size: 14px; font-weight: 700; color: var(--near-black); margin: 0 0 12px 0; display: flex; align-items: center; gap: 6px; }.lfmall-comment-wf .input-wrap { display: flex; gap: 8px; margin-bottom: 16px; }.lfmall-comment-wf .input-box { flex: 1; padding: 10px 12px; border: 1px solid var(--hairline); font-size: 12px; border-radius: 0; }.lfmall-comment-wf .btn-write { background: var(--near-black); color: white; border: none; padding: 0 20px; font-size: 12px; font-weight: 700; cursor: pointer; border-radius: 0; }.lfmall-comment-wf .comm-list { display: flex; flex-direction: column; gap: 10px; }.lfmall-comment-wf .comm-item { border-bottom: 1px dashed var(--hairline); padding-bottom: 8px; font-size: 12px; line-height: 1.5; text-align: left; }.lfmall-comment-wf .comm-item:last-child { border-bottom: none; padding-bottom: 0; }.lfmall-comment-wf .comm-author { font-weight: 700; color: var(--near-black); margin-bottom: 2px; }.lfmall-comment-wf .comm-content { color: var(--slate); }</style><h4 class='comm-title'>💬 실시간 기대평 댓글 (284)</h4><div class='input-wrap'><input type='text' class='input-box' placeholder='이벤트 기대평 및 댓글을 작성해 주세요...'><button class='btn-write' onclick=\"(function(btn){ const val=btn.previousElementSibling.value.trim(); if(!val){ alert('댓글을 입력해주세요.'); return; } alert('댓글이 성공적으로 등록되었습니다! 📝'); btn.previousElementSibling.value=''; })(this)\">등록</button></div><div class='comm-list'><div class='comm-item'><div class='comm-author'>lfm*** (1분 전)</div><div class='comm-content'>헤지스 시어서커 반팔 셔츠 보자마자 바로 지릅니다! 너무 이뻐요.</div></div><div class='comm-item'><div class='comm-author'>hzz*** (10분 전)</div><div class='comm-content'>이번 기획전 혜택이 장난 아니네요. 룰렛 이벤트 최고입니다!</div></div></div></div>"
                   };
