// LFmall Exhibition Wireframe: ENTCODE
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["ENTCODE"] = {
                       "moduleCode":  "MD13",
                       "name":  "입장코드 (ENTCODE)",
                       "wireframeHtml":  "<div class='lfmall-entcode-wf' style='border: 1px solid var(--hairline); background: var(--canvas-white); font-family: \"Malgun Gothic\", \"Apple SD Gothic Neo\", sans-serif; box-shadow: 0 12px 30px rgba(0,0,0,0.02); padding: 32px 20px; text-align: center; border-radius: 0;'><style>.lfmall-entcode-wf .code-badge { font-family: \"Space Mono\", monospace; font-size: 11px; font-weight: 700; color: var(--coral); letter-spacing: 1.5px; text-transform: uppercase; margin-bottom: 6px; display: block; }.lfmall-entcode-wf .code-title { font-size: 20px; font-weight: 800; color: var(--near-black); margin: 0 0 16px 0; letter-spacing: -0.5px; }.lfmall-entcode-wf .input-group { display: flex; justify-content: center; gap: 8px; max-width: 360px; margin: 0 auto; }.desktop-mockup .lfmall-entcode-wf .input-group { flex-direction: row; }.phone-mockup .lfmall-entcode-wf .input-group { flex-direction: column; }.lfmall-entcode-wf .input-box { flex: 1; padding: 10px 14px; border: 1px solid var(--hairline); border-radius: 0; font-size: 13px; color: var(--near-black); }.lfmall-entcode-wf .btn-submit { background: var(--near-black); color: white; border: none; padding: 10px 24px; border-radius: 0; font-size: 13px; font-weight: 700; cursor: pointer; }.title-sec { text-align: center; padding: 24px 16px 12px 16px; }.title-main { font-size: 24px; font-weight: 800; color: var(--near-black); letter-spacing: -0.8px; margin: 0; }.title-sub { font-size: 13px; color: var(--slate); margin: 6px 0 0 0; }</style><div class='title-sec'><h3 class='title-main'>프라이빗 기획전 입장</h3><p class='title-sub'>초대받으신 고객님 전용 프라이빗 입장 코드를 입력해 주세요.</p></div><span class='code-badge'>ENTER PRIVATE CODE</span><h3 class='code-title'>비밀 기획전 입장 코드</h3><div class='input-group'><input type='password' class='input-box' placeholder='비밀 코드를 입력하세요 (예: LFSECRET)'><button class='btn-submit' onclick=\"(function(btn){ const val = btn.previousElementSibling.value.trim(); if(val === 'LFSECRET'){ alert('비밀 기획전 입장 인증이 완료되었습니다! 🔓'); } else { alert('입장 코드가 올바르지 않습니다.'); } })(this)\">입장하기</button></div></div>"
                   };
