// LFmall Exhibition Wireframe: FCFS_CPN_P
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["FCFS_CPN_P"] = {
                       "moduleCode":  "MD6",
                       "name":  "선착순쿠폰상품 (FCFS_CPN_P)",
                       "wireframeHtml":  "<div class='lfmall-fcfs-cpnp-wf' style='border: 1px solid var(--hairline); background: var(--canvas-white); font-family: \"Malgun Gothic\", \"Apple SD Gothic Neo\", sans-serif; box-shadow: 0 12px 30px rgba(0,0,0,0.02); padding: 24px 20px; border-radius: 0;'><style>.lfmall-fcfs-cpnp-wf .tag-line { background: var(--enterprise-green); color: white; font-size: 9px; font-weight: 700; padding: 2px 6px; display: inline-block; text-transform: uppercase; margin-bottom: 10px; }.lfmall-fcfs-cpnp-wf .content-row { display: flex; gap: 16px; align-items: center; text-align: left; }.lfmall-fcfs-cpnp-wf .img-box { width: 80px; height: 80px; background: var(--soft-stone); overflow: hidden; flex-shrink: 0; }.lfmall-fcfs-cpnp-wf .img-box img { width: 100%; height: 100%; object-fit: cover; }.lfmall-fcfs-cpnp-wf .info-box { flex: 1; min-width: 0; }.lfmall-fcfs-cpnp-wf .prod-brand { font-size: 10px; font-weight: 700; color: var(--muted-slate); text-transform: uppercase; }.lfmall-fcfs-cpnp-wf .prod-title { font-size: 14px; font-weight: 700; color: var(--near-black); margin: 2px 0 6px 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.lfmall-fcfs-cpnp-wf .price-row { display: flex; align-items: baseline; gap: 6px; }.lfmall-fcfs-cpnp-wf .price-val { font-size: 16px; font-weight: 800; color: var(--coral); }.lfmall-fcfs-cpnp-wf .price-orig { font-size: 11px; color: var(--muted-slate); text-decoration: line-through; }.title-sec { text-align: center; padding: 24px 16px 12px 16px; }.title-main { font-size: 24px; font-weight: 800; color: var(--near-black); letter-spacing: -0.8px; margin: 0; }.title-sub { font-size: 13px; color: var(--slate); margin: 6px 0 0 0; }</style><div class='title-sec'><h3 class='title-main'>선착순쿠폰상품</h3><p class='title-sub'>매일 한정 수량! 쿠폰 적용 특별가 상품입니다.</p></div><div class='content-row'><div class='img-box'><img src='https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=200&q=80' alt='쿠폰 적용 상품' onerror=\"this.src='data:image/svg+xml;utf8,<svg xmlns=\\\'http://www.w3.org/2000/svg\\\' width=\\\'80\\\' height=\\\'80\\\'><rect width=\\\'80\\\' height=\\\'80\\\' fill=\\\'%23eeece7\\\'/><text x=\\\'50%\\\' y=\\\'60%\\\' font-size=\\\'10\\\' fill=\\\'%2375758a\\\' text-anchor=\\\'middle\\\'>Product</text></svg>';\"></div><div class='info-box'><div class='prod-brand'>ATHE VANESSABRUNO</div><h4 class='prod-title'>[선착순 쿠폰가] 프렌치 린넨 머플러 원피스 세트</h4><div class='price-row'><span class='price-val'>₩ 39,000</span><span class='price-orig'>₩ 78,000</span></div></div></div></div>"
                   };
