// LFmall Exhibition Wireframe: TEXT
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["TEXT"] = {
                 "moduleCode":  "MD2",
                 "name":  "텍스트 (TEXT)",
                 "wireframeHtml":  "<div class='intro-v2-container'><style>.desktop-mockup .intro-v2-container .intro-pc { display: block; }.desktop-mockup .intro-v2-container .intro-mobile { display: none; }.phone-mockup .intro-v2-container .intro-pc { display: none; }.phone-mockup .intro-v2-container .intro-mobile { display: block; }.intro-v2-container { width: 100%; border: 1px solid var(--hairline); border-radius: 0px; overflow: hidden; background: #ffffff; box-sizing: border-box; }.intro-pc { box-sizing: border-box; width: 100%; padding: 60px 10%; color: #111111; font-family: 'Malgun Gothic', 'Apple SD Gothic Neo', sans-serif; text-align: center; word-break: keep-all; }.intro-pc h2 { font-size: 28px; font-weight: 600; line-height: 38px; color: #111111; margin: 0 0 10px 0; letter-spacing: -0.18px; }.intro-pc p.sub-title { font-size: 18px; font-weight: 400; color: #333333; line-height: 26px; margin: 0 auto 20px auto; letter-spacing: -0.1px; }.intro-pc p.content { font-size: 16px; font-weight: 400; color: #666666; line-height: 26px; max-width: 680px; margin: 0 auto 24px auto; letter-spacing: -0.1px; }.intro-pc .date { font-weight: 400 !important; font-size: 14px !important; color: #888888 !important; margin-top: 15px; }.intro-mobile { box-sizing: border-box; width: 100%; padding: 45px 20px; color: #111111; font-family: 'Malgun Gothic', 'Apple SD Gothic Neo', sans-serif; text-align: center; word-break: keep-all; }.intro-mobile h2 { font-size: 22px; font-weight: 600; line-height: 28px; color: #111111; margin: 0 auto 8px auto; letter-spacing: -0.1px; }.intro-mobile p.sub-title { font-size: 15px; font-weight: 400; color: #333333; line-height: 22px; margin: 0 auto 16px auto; letter-spacing: -0.1px; }.intro-mobile p.content { font-size: 14px; font-weight: 400; color: #666666; line-height: 22px; margin: 0 auto 20px auto; letter-spacing: -0.1px; }.intro-mobile .date { font-weight: 600 !important; font-size: 13px !important; color: #888888 !important; margin-top: 10px; }</style><div class='intro-pc'><h2>2026 SUMMER SEASON<br>EDITORIAL EDITION</h2><p class='sub-title'>LFmall Premium Editorial Collection</p><p class='content'>자유롭고 감각적인 실루엣과 고급스러운 소재감이 조화를 이루는 LFmall만의 특별한 제안. 한여름의 쾌적함과 품격을 동시에 선사하는 프리미엄 컬렉션을 지금 만나보세요.</p><p class='date'>2026.06.01 - 2026.06.30</p></div><div class='intro-mobile'><h2>2026 SUMMER SEASON<br>EDITORIAL EDITION</h2><p class='sub-title'>LFmall Premium Editorial Collection</p><p class='content'>자유롭고 감각적인 실루엣과 고급스러운 소재감이 조화를 이루는 LFmall만의 특별한 제안. 한여름의 쾌적함과 품격을 동시에 선사하는 프리미엄 컬렉션을 지금 만나보세요.</p><p class='date'>2026.06.01 - 2026.06.30</p></div></div>"
             };
