// LFmall Exhibition Wireframe: TEXT
// Auto-generated from db_wireframes.js split.
// Do NOT edit the header. Edit wireframeHtml only.

window.ExhibitionWireframes = window.ExhibitionWireframes || {};
window.ExhibitionWireframes["TEXT"] = {
                 "moduleCode":  "MD2",
                 "name":  "텍스트 (TEXT)",
                 "wireframeHtml":  "<div class=\u0027lfmall-text-wf\u0027 style=\u0027border: 1px solid var(--hairline); background: var(--canvas-white); overflow: hidden; font-family: \"Malgun Gothic\", \"Apple SD Gothic Neo\", sans-serif; box-shadow: 0 12px 30px rgba(0,0,0,0.02); padding: 48px 24px; text-align: center;\u0027><style>.lfmall-text-wf { position: relative; }.lfmall-text-wf .badge { display: inline-block; font-size: 11px; font-weight: 700; color: var(--coral); letter-spacing: 2px; text-transform: uppercase; margin-bottom: 12px; font-family: \"Space Mono\", monospace; }.lfmall-text-wf .main-title { font-size: 26px; font-weight: 800; color: var(--near-black); line-height: 1.35; letter-spacing: -0.8px; margin: 0 auto 16px; max-width: 600px; }.lfmall-text-wf .divider { width: 40px; height: 2px; background: var(--near-black); margin: 20px auto; }.lfmall-text-wf .intro-content { font-size: 14px; font-weight: 400; color: var(--slate); line-height: 1.65; letter-spacing: -0.3px; max-width: 520px; margin: 0 auto; text-align: center; word-break: keep-all; }.lfmall-text-wf .period-box { margin-top: 24px; font-size: 11px; font-weight: 600; color: var(--near-black); letter-spacing: -0.1px; display: inline-flex; align-items: center; gap: 6px; background: var(--soft-stone); padding: 6px 14px; border-radius: 4px; }.title-sec { text-align: center; padding: 24px 16px 12px 16px; }.title-main { font-size: 24px; font-weight: 800; color: var(--near-black); letter-spacing: -0.8px; margin: 0; }.title-sub { font-size: 13px; color: var(--slate); margin: 6px 0 0 0; }</style><div class='title-sec'><h3 class='title-main'>이벤트 상세 안내</h3><p class='title-sub'>기획전 참여 및 혜택 적용을 위한 상세 안내 사항입니다.</p></div><span class=\u0027badge\u0027>Seasonal Concept</span><h2 class=\u0027main-title\u0027>2026 SUMMER SEASON<br>EDITORIAL EDITION</h2><div class=\u0027divider\u0027></div><p class=\u0027intro-content\u0027>자유롭고 감각적인 실루엣과 고급스러운 소재감이 조화를 이루는 LFmall만의 특별한 제안. 한여름의 쾌적함과 품격을 동시에 선사하는 프리미엄 컬렉션을 지금 만나보세요.</p><div class=\u0027period-box\u0027><span>📅</span> 2026.06.01 10:00 ~ 2026.06.30 23:59</div></div>"
             };
